name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install
          
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clean unnecessary files
        run: |
          # Remove any existing database files
          rm -rf embeddings/chroma_db
          rm -rf .chroma
          rm -f *.sqlite3
          rm -f *.db
          
          # Create necessary directories
          mkdir -p data/uploads data/chatlogs

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Clean build for Hugging Face" || echo "No changes to commit"
          git remote add space https://anandan-bs:$HF_TOKEN@huggingface.co/spaces/anandan-bs/ollama-rag-engine
          git push --force space main
